application: rngapp
version: dev
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^Gruntfile\.js
- ^node_modules/(.*/)?
- ^(.*)\.scss$

handlers:
- url: /video/(.*\.(gif|png|jpg|mp4|ogv|webm))
  static_files: video/\1
  upload: video/(.*\.(gif|png|jpg|mp4|ogv|webm))

- url: /(.*\.ogv)
  static_files: video/\1
  mime_type: video/ogg
  upload: video/(.*\.ogv)

- url: /(.*\.mp4)
  static_files: video/\1
  mime_type: video/mp4
  upload: video/(.*\.mp4)

- url: /(.*\.webm)
  static_files: video/\1
  mime_type: video/webm
  upload: video/(.*\.webm)

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /\.tmp
  static_dir: \.tmp

- url: /scripts
  mime_type: text/javascript
  static_dir: scripts

- url: /components
  static_dir: components

- url: /views
  static_dir: views

- url: /styles
  mime_type: text/css
  static_dir: styles

- url: /img/(.*\.(gif|png|jpg))
  static_files: img/\1
  upload: img/(.*\.(gif|png|jpg))

# - url: /admin/.*
#   script: main.app
#   login: admin

- url: /api/(.*)
  script: main.app

- url: .*
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: pycrypto
  version: "2.6"

